#! /bin/bash

#PBS -N MPIMARKDUP_MYSAM_4_JOBS
#PBS -l	nodes=2:ppn=2:mem=${MEM}     	# Ask 2 nodes and 2 jobs per node
#PBS -l walltime=24:00:00
#PBS -o STDOUT_FILE.%j.o
#PBS -e STDERR_FILE.%j.e

type mpiMarkDup

if [[ ! $? -eq 0 ]]
then
    echo "ERROR: mpiMarkDup not found in your PATH"
    exit 1
fi

output_dir=${HOME}/mpiMarkDupExample

if [[ ! -d ${output_dir} ]]
then
    mkdir -p ${output_dir}
    echo "INFO: the directory ${output_dir} has been created to store the results generated by mpiMarkDupExample"
fi

cd ${PBS_O_WORKDIR}

mpirun -n 4 mpiMarkDup data/HCC1187C_70K_READS.sam ${output_dir}  -q 0 -d 1000 2> ${output_dir}/mpiMarkDup.log

echo "INFO: mpiMarkDup.log is available in ${output_dir}"

