#! /bin/bash

#SBATCH -J MPIMARKDUP_MYSAM_4_JOBS
#SBATCH -N 2                       	# Ask 2 nodes
#SBATCH -n 4                       	# Total number of cores
#SBATCH -c 1			   	# use 1 core per mpi job
#SBATCH --tasks-per-node=2         	# Ask 2 cores per node
#SBATCH --mem-per-cpu=${MEM}	   	# See Memory ressources
#SBATCH -t 01:00:00
#SBATCH -o STDOUT_FILE.%j.o
#SBATCH -e STDERR_FILE.%j.e

type mpiMarkDup

if [[ ! $? -eq 0 ]]
then
    echo "ERROR: mpiMarkDup not found in your PATH"
    exit 1
fi

output_dir=${HOME}/mpiMarkDupExample

if [[ ! -d ${output_dir} ]]
then
    mkdir -p ${output_dir}
    echo "INFO: the directory ${output_dir} has been created to store the results generated by mpiMarkDupExample"
fi

cd ${SLURM_SUBMIT_DIR}

mpirun -n 4 mpiMarkDup data/HCC1187C_70K_READS.sam ${output_dir}  -q 0 -d 1000 2> ${output_dir}/mpiMarkDup.log

echo "INFO: mpiMarkDup.log is available in ${output_dir}"

