#! /bin/bash

type mpiMarkDup

if [[ ! $? -eq 0 ]]
then
    echo "ERROR: mpiMarkDup not found in your PATH"
    exit 1
fi

output_dir=${HOME}/mpiMarkDupExample

if [[ ! -d ${output_dir} ]]
then
    mkdir -p ${output_dir}
    echo "INFO: the directory ${output_dir} has been created to store the results generated by mpiMarkDupExample"
fi

mpirun -n 4 mpiMarkDup data/HCC1187C_70K_READS.sam ${output_dir}  -q 0 -d 1000 2> ${output_dir}/mpiMarkDup.log

echo "INFO: mpiMarkDup.log is available in ${output_dir}"

